import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import Header from "./header";
import AppFooter from "./footer";
import AppTable from "./table";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />

        <div className="container">{children}</div>
        <AppFooter />
      </body>
    </html>
  );
}
